### ISSUE TITLE
Caracteres Especiais

### ISSUE THREAD

**Issue by Miguel-Frazao** [nmota/caop_GeoJSON#1]
Antes de mais quero dar-lhe os parabéns por excelente trabalho.

Estou de momento a desenvolver um projeto que vou precisar dos geojsons dos distritos, concelhos e freguesias de portugal. No entanto parece ter havido um problema com os caracteres especiais (acentoados, "ç", etc...) na geração destes jsons, como é o caso do primeiro concelho desde link: https://raw.githubusercontent.com/nmota/caop_GeoJSON/master/ContinenteConcelhos.geojson , logo o primeiro concelho "ÁGUEDA" que está "�GUEDA". Pedia-lhe os ficheiros base para estes jsons, ou que corrija no seu repositório, se faz favor. 

Obrigado,

**Comment by nmota** [comment]
Penso que corrigi o problema. Diga-me se estiver tudo bem para fechar este issue.
Não existem ficheiros base para estes jsons, o README diz claramente qual a sua origem mas se tiver alguma dúvida é só perguntar.

Agradeço o interesse,

**Comment by Miguel-Frazao** [comment]
Muito Obrigado, acho que se pode fechar este issue. Obrigado por partilhar
