### ISSUE TITLE
Poligonos no sistema de coordenadas latitude/longitude

### ISSUE THREAD

**Issue by nribeiro90old** [nmota/caop_GeoJSON#2]
Olá,

Não é propriamente uma issue, mas cá vai.

Existe alguma forma de converter o sistema de coordenadas para latitude / longitude?

Cumprimentos,
Nuno

**Comment by nmota** [comment]
Olá @nribeiro90,

Claro! Penso que a forma mais fácil é produzir os ficheiros geoJSON com coordenadas geográficas em vez de cartográficas.

Posso publicar assim que tiver algum tempo.

**Comment by nribeiro90old** [comment]
Thank you @nmota ! 👍
